import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ServerUI {
    private JPanel panel1;
    private JRadioButton serverOnRadioButton;
    private JPanel panel2;
    private JTextPane textPane1;
    private JButton button1;
    private JTextField textField1;
    Server server;

    public ServerUI() {
        serverOnRadioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                if (serverOnRadioButton.isSelected()) {
                    server = new Server(textPane1);
                    new Thread(server).start();
                    textField1.setEnabled(true);
                } else {
                    server.stop();
                    textField1.setEnabled(false);
                }
            }
        });

        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                JFrame f = new JFrame("ClientUI");
                f.setBounds(100 + 320 + 20, 100, 320, 240);
                f.setContentPane(new ClientUI().$$$getRootComponent$$$());
                f.setVisible(true);
            }
        });

        textField1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                textField1.setText("");
                if (!actionEvent.getActionCommand().contains("exit")) {
                    server.out.println(actionEvent.getActionCommand());
                    textPane1.setText(textPane1.getText() + "<= " + actionEvent.getActionCommand() + "\r\n");
                } else {
                    server.stop();
                    textField1.setEnabled(false);
                    serverOnRadioButton.setSelected(false);
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JToolBar toolBar1 = new JToolBar();
        panel1.add(toolBar1, BorderLayout.SOUTH);
        serverOnRadioButton = new JRadioButton();
        serverOnRadioButton.setText("On");
        toolBar1.add(serverOnRadioButton);
        button1 = new JButton();
        button1.setText("+C");
        toolBar1.add(button1);
        textField1 = new JTextField();
        textField1.setEnabled(false);
        textField1.setText("");
        toolBar1.add(textField1);
        panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, BorderLayout.CENTER);
        textPane1 = new JTextPane();
        textPane1.setEditable(false);
        textPane1.setEnabled(true);
        scrollPane1.setViewportView(textPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
